# Generated by Django 6.0.5 on 2026-05-23 17:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_blood_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPartographEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hours_in_labour', models.DecimalField(decimal_places=1, help_text='Hours elapsed since active labour onset (0–24)', max_digits=4)),
                ('recorded_at', models.DateTimeField(blank=True, editable=False)),
                ('cervical_dilation_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Cervical dilation in cm (0–10)', max_digits=3, null=True)),
                ('descent_station', models.IntegerField(blank=True, help_text='Station of presenting part (-5 to +5)', null=True)),
                ('fetal_heart_rate', models.IntegerField(blank=True, help_text='Fetal heart rate in bpm (60–200)', null=True)),
                ('moulding', models.CharField(blank=True, choices=[('0', 'None'), ('1', '+'), ('2', '++'), ('3', '+++')], default='0', max_length=1)),
                ('liquor', models.CharField(blank=True, choices=[('I', 'Intact'), ('C', 'Clear'), ('M', 'Meconium'), ('B', 'Blood'), ('A', 'Absent')], default='I', max_length=1)),
                ('contractions_per_10min', models.IntegerField(blank=True, help_text='Number of contractions per 10 minutes (0–5)', null=True)),
                ('contraction_duration', models.CharField(blank=True, choices=[('<20', '< 20 sec'), ('20-40', '20–40 sec'), ('>40', '> 40 sec')], max_length=5)),
                ('bp_systolic', models.IntegerField(blank=True, help_text='Systolic BP mmHg', null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, help_text='Diastolic BP mmHg', null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text='Maternal pulse bpm', null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('urine_volume_ml', models.IntegerField(blank=True, null=True)),
                ('urine_protein', models.CharField(blank=True, choices=[('NIL', 'Nil'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NIL', max_length=3)),
                ('oxytocin_units', models.IntegerField(blank=True, help_text='Oxytocin units/L', null=True)),
                ('iv_fluids_ml', models.IntegerField(blank=True, null=True)),
                ('drugs_given', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Partograph Entry',
                'verbose_name_plural': 'historical Partograph Entrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('patient_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('lmp', models.DateField(verbose_name='Last Menstrual Period')),
                ('edd', models.DateField(blank=True, verbose_name='Expected Delivery Date')),
                ('clinic_stage', models.CharField(choices=[('ANC1', 'ANC Visit 1'), ('ANC2', 'ANC Visit 2'), ('ANC3', 'ANC Visit 3'), ('ANC4', 'ANC Visit 4'), ('DELIVERED', 'Delivered'), ('POSTNATAL', 'Postnatal')], default='ANC1', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=5)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical patient',
                'verbose_name_plural': 'historical patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PartographEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_in_labour', models.DecimalField(decimal_places=1, help_text='Hours elapsed since active labour onset (0–24)', max_digits=4)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('cervical_dilation_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Cervical dilation in cm (0–10)', max_digits=3, null=True)),
                ('descent_station', models.IntegerField(blank=True, help_text='Station of presenting part (-5 to +5)', null=True)),
                ('fetal_heart_rate', models.IntegerField(blank=True, help_text='Fetal heart rate in bpm (60–200)', null=True)),
                ('moulding', models.CharField(blank=True, choices=[('0', 'None'), ('1', '+'), ('2', '++'), ('3', '+++')], default='0', max_length=1)),
                ('liquor', models.CharField(blank=True, choices=[('I', 'Intact'), ('C', 'Clear'), ('M', 'Meconium'), ('B', 'Blood'), ('A', 'Absent')], default='I', max_length=1)),
                ('contractions_per_10min', models.IntegerField(blank=True, help_text='Number of contractions per 10 minutes (0–5)', null=True)),
                ('contraction_duration', models.CharField(blank=True, choices=[('<20', '< 20 sec'), ('20-40', '20–40 sec'), ('>40', '> 40 sec')], max_length=5)),
                ('bp_systolic', models.IntegerField(blank=True, help_text='Systolic BP mmHg', null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, help_text='Diastolic BP mmHg', null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text='Maternal pulse bpm', null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('urine_volume_ml', models.IntegerField(blank=True, null=True)),
                ('urine_protein', models.CharField(blank=True, choices=[('NIL', 'Nil'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NIL', max_length=3)),
                ('oxytocin_units', models.IntegerField(blank=True, help_text='Oxytocin units/L', null=True)),
                ('iv_fluids_ml', models.IntegerField(blank=True, null=True)),
                ('drugs_given', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partograph_entries', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partograph_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partograph Entry',
                'db_table': 'partograph_entries',
                'ordering': ['hours_in_labour'],
            },
        ),
    ]
