# Generated by Django 6.0.5 on 2026-05-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_historicalpartographentry_historicalpatient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='National ID'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='nhif_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NHIF Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='National ID'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nhif_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NHIF Number'),
        ),
    ]
