# Generated by Django 6.0.5 on 2026-06-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_historicalpatient_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='surgical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='surgical_history',
            field=models.TextField(blank=True),
        ),
    ]
