# Generated by Django 6.0.5 on 2026-06-04 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_historicalpatient_allergies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['edd'], name='patients_edd_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['risk_level'], name='patients_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic_stage'], name='patients_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='patients_active_idx'),
        ),
    ]
