# Generated by Django 6.0.5 on 2026-06-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_patients_edd_idx_patient_patients_risk_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=2, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=2, verbose_name='Preferred Language'),
        ),
    ]
