# Generated by Django 5.0.9 on 2026-06-05 09:18

import core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_historicalpatient_lang_patient_lang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='national_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='nhif_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='phone_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nhif_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='national_id',
            field=core.fields.EncryptedCharField(blank=True, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nhif_number',
            field=core.fields.EncryptedCharField(blank=True, null=True, verbose_name='NHIF Number'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='phone_number',
            field=core.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=core.fields.EncryptedCharField(blank=True, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nhif_number',
            field=core.fields.EncryptedCharField(blank=True, null=True, verbose_name='NHIF Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=core.fields.EncryptedCharField(),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id_hash'], name='patients_nat_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nhif_number_hash'], name='patients_nhif_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number_hash'], name='patients_ph_hash_idx'),
        ),
    ]
