# Generated by Django 6.0.5 on 2026-06-05 09:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_historicalpatient_lang_patient_lang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPatientAllergy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('allergen', models.CharField(max_length=200)),
                ('reaction', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=10)),
                ('first_noted', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Maternal Allergy',
                'verbose_name_plural': 'historical Maternal Allergys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatientFamilyHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('relation', models.CharField(blank=True, choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('SIBLING', 'Sibling'), ('GRANDPARENT', 'Grandparent'), ('OTHER', 'Other')], max_length=50)),
                ('condition', models.CharField(max_length=200)),
                ('age_at_diagnosis', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Family History Entry',
                'verbose_name_plural': 'historical Family History Entrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatientMedicalCondition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('KNOWN', 'Known'), ('ONGOING', 'Ongoing'), ('RESOLVED', 'Resolved'), ('UNKNOWN', 'Unknown')], default='KNOWN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Maternal Medical Condition',
                'verbose_name_plural': 'historical Maternal Medical Conditions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatientSurgicalHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
                ('procedure_date', models.DateField(blank=True, null=True)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('outcome', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Maternal Surgical History',
                'verbose_name_plural': 'historical Maternal Surgical Historys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=200)),
                ('reaction', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=10)),
                ('first_noted', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maternal Allergy',
                'db_table': 'patient_allergies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientFamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('SIBLING', 'Sibling'), ('GRANDPARENT', 'Grandparent'), ('OTHER', 'Other')], max_length=50)),
                ('condition', models.CharField(max_length=200)),
                ('age_at_diagnosis', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family History Entry',
                'db_table': 'patient_family_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('KNOWN', 'Known'), ('ONGOING', 'Ongoing'), ('RESOLVED', 'Resolved'), ('UNKNOWN', 'Unknown')], default='KNOWN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maternal Medical Condition',
                'db_table': 'patient_medical_conditions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientSurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
                ('procedure_date', models.DateField(blank=True, null=True)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('outcome', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maternal Surgical History',
                'db_table': 'patient_surgical_histories',
                'ordering': ['-procedure_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='birth_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='birth_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='education_level',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary'), ('UNIVERSITY', 'University'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='emergency_contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], default='FEMALE', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='household_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of people in household', null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('COHABITING', 'Cohabiting'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='profile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='registration_stage',
            field=models.CharField(choices=[('NEW', 'New Registration'), ('IDENTITY_CAPTURED', 'Identity Captured'), ('PROFILE_COMPLETE', 'Profile Complete'), ('VERIFIED', 'Verified'), ('UPDATED', 'Updated')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='residence_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='residence_subcounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='residence_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='residence_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='education_level',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary'), ('UNIVERSITY', 'University'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], default='FEMALE', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='household_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of people in household', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('COHABITING', 'Cohabiting'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_stage',
            field=models.CharField(choices=[('NEW', 'New Registration'), ('IDENTITY_CAPTURED', 'Identity Captured'), ('PROFILE_COMPLETE', 'Profile Complete'), ('VERIFIED', 'Verified'), ('UPDATED', 'Updated')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence_subcounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['registration_stage'], name='patient_reg_stage_idx'),
        ),
        migrations.AddField(
            model_name='historicalpatientallergy',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatientallergy',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='historicalpatientfamilyhistory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatientfamilyhistory',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='historicalpatientmedicalcondition',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatientmedicalcondition',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='historicalpatientsurgicalhistory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatientsurgicalhistory',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_entries', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientfamilyhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history_entries', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientmedicalcondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_entries', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientsurgicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_history_entries', to='patients.patient'),
        ),
    ]
