# Generated by Django 5.0.9 on 2026-06-05 09:18

from django.db import migrations
import hashlib
from cryptography.fernet import Fernet
from django.conf import settings

def encrypt_and_hash_existing_data(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    
    # Initialize Fernet cipher using the settings key
    key = getattr(settings, 'FIELD_ENCRYPTION_KEY', None)
    if not key:
        key = 'Z7iHf1QHDFlUrNFPBIRzUKsitZbK1trKw4K5XFuduiI='
    if isinstance(key, str):
        key = key.encode('utf-8')
    cipher = Fernet(key)

    for patient in Patient.objects.all():
        updated = False
        
        # 1. phone_number
        if patient.phone_number:
            raw_phone = patient.phone_number.strip()
            if raw_phone.startswith('gAAAA'):
                try:
                    raw_phone = cipher.decrypt(raw_phone.encode('utf-8')).decode('utf-8').strip()
                except Exception:
                    pass
            patient.phone_number = raw_phone
            patient.phone_number_hash = hashlib.sha256(raw_phone.encode('utf-8')).hexdigest()
            updated = True

        # 2. national_id
        if patient.national_id:
            raw_id = patient.national_id.strip()
            if raw_id.startswith('gAAAA'):
                try:
                    raw_id = cipher.decrypt(raw_id.encode('utf-8')).decode('utf-8').strip()
                except Exception:
                    pass
            patient.national_id = raw_id
            patient.national_id_hash = hashlib.sha256(raw_id.encode('utf-8')).hexdigest()
            updated = True

        # 3. nhif_number
        if patient.nhif_number:
            raw_nhif = patient.nhif_number.strip()
            if raw_nhif.startswith('gAAAA'):
                try:
                    raw_nhif = cipher.decrypt(raw_nhif.encode('utf-8')).decode('utf-8').strip()
                except Exception:
                    pass
            patient.nhif_number = raw_nhif
            patient.nhif_number_hash = hashlib.sha256(raw_nhif.encode('utf-8')).hexdigest()
            updated = True

        if updated:
            patient.save()

def reverse_encrypt_data(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    key = getattr(settings, 'FIELD_ENCRYPTION_KEY', None)
    if not key:
        key = 'Z7iHf1QHDFlUrNFPBIRzUKsitZbK1trKw4K5XFuduiI='
    if isinstance(key, str):
        key = key.encode('utf-8')
    cipher = Fernet(key)

    for patient in Patient.objects.all():
        updated = False
        
        if patient.phone_number and patient.phone_number.startswith('gAAAA'):
            try:
                patient.phone_number = cipher.decrypt(patient.phone_number.encode('utf-8')).decode('utf-8')
                patient.phone_number_hash = None
                updated = True
            except Exception:
                pass

        if patient.national_id and patient.national_id.startswith('gAAAA'):
            try:
                patient.national_id = cipher.decrypt(patient.national_id.encode('utf-8')).decode('utf-8')
                patient.national_id_hash = None
                updated = True
            except Exception:
                pass

        if patient.nhif_number and patient.nhif_number.startswith('gAAAA'):
            try:
                patient.nhif_number = cipher.decrypt(patient.nhif_number.encode('utf-8')).decode('utf-8')
                patient.nhif_number_hash = None
                updated = True
            except Exception:
                pass

        if updated:
            patient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_historicalpatient_national_id_hash_and_more'),
    ]

    operations = [
        migrations.RunPython(encrypt_and_hash_existing_data, reverse_encrypt_data),
    ]
