# Generated by Django 6.0.5 on 2026-06-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_historicalpatientallergy_and_more'),
        ('patients', '0009_encrypt_existing_patient_data'),
    ]

    operations = [
    ]
