# Generated by Django 5.0.9 on 2026-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_merge_20260605_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='anc_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='blood_transfusion_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='drug_allergies_specify',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='estate_house_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='family_history_tb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='family_history_twins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='gravida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='has_drug_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='has_hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='health_facility_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='kmhfl_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='parity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='pnc_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='tb_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='anc_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_transfusion_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_allergies_specify',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='estate_house_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_tb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_twins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='gravida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_drug_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_facility_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='kmhfl_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='parity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pnc_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='tb_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
