# Generated by Django 6.0.5 on 2026-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_add_symptom_report_and_secure_message'),
    ]

    operations = [
        # Alter national_id to TEXT to handle encrypted values
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.TextField(blank=True, null=True, verbose_name='National ID'),
        ),
        # Alter nhif_number to TEXT to handle encrypted values
        migrations.AlterField(
            model_name='patient',
            name='nhif_number',
            field=models.TextField(blank=True, null=True, verbose_name='NHIF Number'),
        ),
        # Also update historical patient model
        migrations.AlterField(
            model_name='historicalpatient',
            name='national_id',
            field=models.TextField(blank=True, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nhif_number',
            field=models.TextField(blank=True, null=True, verbose_name='NHIF Number'),
        ),
    ]