# Generated by Django 6.0.5 on 2026-06-08 09:08

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_national_id_and_nhif_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='national_id',
            field=core.fields.EncryptedCharField(blank=True, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nhif_number',
            field=core.fields.EncryptedCharField(blank=True, null=True, verbose_name='NHIF Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=core.fields.EncryptedCharField(blank=True, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nhif_number',
            field=core.fields.EncryptedCharField(blank=True, null=True, verbose_name='NHIF Number'),
        ),
    ]
