# Generated by Django 6.0.5 on 2026-06-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_widen_encrypted_patient_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomreport',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Comma-separated or text list of symptoms (e.g. bleeding, severe_headache, swelling, fever, reduced_fetal_movement)'),
        ),
    ]
