# Generated by Django 6.0.5 on 2026-06-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_care_alert_follow_up'),
        ('patients', '0016_allow_blank_symptom_report_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='securemessage',
            name='clinical_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_messages', to='alerts.clinicalalert'),
        ),
        migrations.AddField(
            model_name='securemessage',
            name='message_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('CARE_ALERT', 'Care Alert')], default='GENERAL', max_length=20),
        ),
    ]
