# Generated by Django 5.0.9 on 2026-06-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_historicalpatient_anc_number_and_more'),
        ('patients', '0017_care_alert_follow_up'),
    ]

    operations = [
    ]
