# Generated by Django 6.0.5 on 2026-06-05 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0007_historicalpatient_lang_patient_lang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalDeathReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField(help_text='Date of death or near-miss event')),
                ('cause_of_death', models.TextField(help_text='Immediate, underlying, or contributing causes of death')),
                ('avoidable_factors', models.TextField(blank=True, help_text='Avoidable factors, missed opportunities, or lapses in care standards')),
                ('three_delays', models.TextField(blank=True, help_text='Delays at community (seeking care), transport (reaching facility), or institutional level (receiving care)')),
                ('recommendations', models.TextField(blank=True, help_text='Recommended remedial actions to prevent recurrence')),
                ('review_date', models.DateField(help_text='Date the clinical audit / review was conducted')),
                ('is_near_miss', models.BooleanField(default=False, help_text='True if this is a maternal near-miss rather than a mortality event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, help_text='The patient associated with this review (can be empty/anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_reviews', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(help_text='Clinician who conducted/logged the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_death_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maternal_mortality_reviews',
                'ordering': ['-date_of_death', '-created_at'],
            },
        ),
    ]
