# Generated by Django 6.0.5 on 2026-06-05 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0007_historicalpatient_lang_patient_lang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KMHFLFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='KMHFL code of the facility', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Official name of the facility', max_length=255)),
                ('county', models.CharField(blank=True, help_text='County where facility is located', max_length=100)),
            ],
            options={
                'verbose_name': 'KMHFL Facility',
                'verbose_name_plural': 'KMHFL Facilities',
                'db_table': 'referral_kmhfl_facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateField(help_text='Date of the referral')),
                ('destination_facility', models.CharField(help_text='KMHFL code + name of destination facility', max_length=255)),
                ('reason', models.TextField(help_text='Reason for referral')),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=20)),
                ('clinical_summary', models.TextField(help_text='Clinical summary of the patient')),
                ('transport_mode', models.CharField(choices=[('AMBULANCE', 'Ambulance'), ('PRIVATE', 'Private Transport'), ('PUBLIC', 'Public Transport')], default='PUBLIC', max_length=20)),
                ('feedback_received', models.BooleanField(default=False, help_text='Has feedback been received from destination facility?')),
                ('outcome_notes', models.TextField(blank=True, help_text='Outcome or feedback notes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient being referred', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
                ('referred_by', models.ForeignKey(help_text='Staff user making the referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-referral_date', '-created_at'],
            },
        ),
    ]
