# Generated by Django 6.0.5 on 2026-05-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_historicalpartographentry_historicalpatient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('phase', models.CharField(choices=[('ANC_T1', 'Antenatal — Trimester 1'), ('ANC_T2', 'Antenatal — Trimester 2'), ('ANC_T3', 'Antenatal — Trimester 3'), ('POSTNATAL_EARLY', 'Postnatal — Early (0–6 weeks)'), ('POSTNATAL_LATE', 'Postnatal — Late (6+ weeks)'), ('LACTATING', 'Lactating')], max_length=20)),
                ('condition_tags', models.CharField(blank=True, help_text='Comma-separated: anaemia, hypertension, diabetes, caesarean', max_length=200)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MORNING_SNACK', 'Morning Snack'), ('LUNCH', 'Lunch'), ('AFTERNOON_SNACK', 'Afternoon Snack'), ('DINNER', 'Dinner'), ('EVENING_SNACK', 'Evening Snack')], max_length=20)),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7')], default=1)),
                ('description', models.TextField(help_text='Full meal description with portions')),
                ('foods', models.TextField(help_text='Comma-separated food items')),
                ('calories_approx', models.PositiveIntegerField(default=0)),
                ('local_alternatives', models.TextField(blank=True, help_text='Locally available alternatives for rural settings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diet_plans',
                'ordering': ['day_of_week', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='NutritionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='🥗', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#2DD4BF', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Nutrition Categories',
                'db_table': 'nutrition_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('OVERRIDDEN', 'Overridden by Doctor')], default='ACTIVE', max_length=15)),
                ('adherence_score', models.PositiveIntegerField(default=0, help_text='0-100 adherence percentage')),
                ('override_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='nutrition.dietplan')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_recommendations', to='patients.patient')),
            ],
            options={
                'db_table': 'diet_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dietplan',
            name='categories',
            field=models.ManyToManyField(blank=True, to='nutrition.nutritioncategory'),
        ),
        migrations.CreateModel(
            name='PatientNutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('ANC_T1', 'Antenatal — Trimester 1'), ('ANC_T2', 'Antenatal — Trimester 2'), ('ANC_T3', 'Antenatal — Trimester 3'), ('POSTNATAL_EARLY', 'Postnatal — Early (0–6 weeks)'), ('POSTNATAL_LATE', 'Postnatal — Late (6+ weeks)'), ('LACTATING', 'Lactating')], default='ANC_T1', max_length=20)),
                ('is_anaemic', models.BooleanField(default=False)),
                ('is_hypertensive', models.BooleanField(default=False)),
                ('is_diabetic', models.BooleanField(default=False)),
                ('is_lactating', models.BooleanField(default=False)),
                ('is_post_caesarean', models.BooleanField(default=False)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_weight_gain_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('calorie_target', models.PositiveIntegerField(default=2200)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated allergens')),
                ('dietary_preferences', models.TextField(blank=True, help_text='e.g. vegetarian, halal')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_nutrition_profiles',
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gestational_week', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weight_logs',
                'ordering': ['recorded_at'],
            },
        ),
    ]
