# Generated by Django 6.0.5 on 2026-05-23 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_historicalpartographentry_historicalpatient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('FHR_LOW', 'Fetal Heart Rate — Low (<110 bpm)'), ('FHR_HIGH', 'Fetal Heart Rate — High (>160 bpm)'), ('BP_CRITICAL', 'Blood Pressure — Critical'), ('ACTION_LINE_CROSSED', 'Labour — Action Line Crossed'), ('ALERT_LINE_CROSSED', 'Labour — Alert Line Crossed'), ('PROLONGED_LABOUR', 'Prolonged Labour (>12 h)'), ('TEMP_HIGH', 'Maternal Temperature — High (>38°C)')], max_length=30)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('value_triggered', models.CharField(blank=True, help_text='The actual value that triggered this alert (e.g. "105 bpm")', max_length=50)),
                ('threshold', models.CharField(blank=True, help_text='The threshold that was breached (e.g. "<110 bpm")', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('partograph_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='patients.partographentry')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_alerts', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Clinical Alert',
                'verbose_name_plural': 'Clinical Alerts',
                'db_table': 'clinical_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'alert_type', 'acknowledged'], name='clinical_al_patient_d8394c_idx'), models.Index(fields=['acknowledged', 'created_at'], name='clinical_al_acknowl_4025d4_idx')],
            },
        ),
    ]
