# Generated by Django 6.0.5 on 2026-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalalert',
            name='alert_type',
            field=models.CharField(choices=[('FHR_LOW', 'Fetal Heart Rate — Low (<110 bpm)'), ('FHR_HIGH', 'Fetal Heart Rate — High (>160 bpm)'), ('BP_CRITICAL', 'Blood Pressure — Critical'), ('ACTION_LINE_CROSSED', 'Labour — Action Line Crossed'), ('ALERT_LINE_CROSSED', 'Labour — Alert Line Crossed'), ('PROLONGED_LABOUR', 'Prolonged Labour (>12 h)'), ('TEMP_HIGH', 'Maternal Temperature — High (>38°C)'), ('PATIENT_SYMPTOM_REPORT', 'Patient Symptom Report (Mother Portal)')], max_length=30),
        ),
    ]
