# Generated by Django 6.0.5 on 2026-06-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_add_patient_symptom_report_alert_type'),
        ('patients', '0016_allow_blank_symptom_report_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalalert',
            name='symptom_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_alerts', to='patients.symptomreport'),
        ),
    ]
