# Generated by Django 6.0.5 on 2026-05-28 05:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_historicalpatient_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField(help_text='e.g. 1 for ANC1, 2 for ANC2')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('hemoglobin_gdl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fundal_height_cm', models.IntegerField(blank=True, null=True)),
                ('fetal_heart_rate', models.IntegerField(blank=True, null=True)),
                ('fetal_presentation', models.CharField(blank=True, choices=[('CEPHALIC', 'Cephalic'), ('BREECH', 'BREECH'), ('TRANSVERSE', 'Transverse')], max_length=15)),
                ('ultrasound_results', models.TextField(blank=True)),
                ('lab_tests_summary', models.TextField(blank=True)),
                ('complications_noted', models.TextField(blank=True, help_text='Notes on any high-risk complications')),
                ('medication_prescribed', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anc_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_visits', to='patients.patient')),
            ],
            options={
                'db_table': 'anc_visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB_ORDER', 'Lab Order'), ('LAB_RESULT', 'Lab Result'), ('PRESCRIPTION', 'Prescription'), ('REFERRAL', 'Referral'), ('OBSERVATION', 'Observation'), ('DISCHARGE', 'Discharge Summary')], default='CONSULTATION', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='ROUTINE', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('diagnosis_codes', models.CharField(blank=True, help_text='Comma-separated ICD-10 codes (e.g. O14.1, O24.4)', max_length=200)),
                ('lab_test_name', models.CharField(blank=True, max_length=200)),
                ('lab_result_value', models.CharField(blank=True, max_length=200)),
                ('lab_result_unit', models.CharField(blank=True, max_length=50)),
                ('lab_reference_range', models.CharField(blank=True, max_length=100)),
                ('lab_is_abnormal', models.BooleanField(default=False)),
                ('medication_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patient')),
            ],
            options={
                'db_table': 'clinical_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalANCVisit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField(help_text='e.g. 1 for ANC1, 2 for ANC2')),
                ('visit_date', models.DateField(blank=True, editable=False)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('hemoglobin_gdl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fundal_height_cm', models.IntegerField(blank=True, null=True)),
                ('fetal_heart_rate', models.IntegerField(blank=True, null=True)),
                ('fetal_presentation', models.CharField(blank=True, choices=[('CEPHALIC', 'Cephalic'), ('BREECH', 'BREECH'), ('TRANSVERSE', 'Transverse')], max_length=15)),
                ('ultrasound_results', models.TextField(blank=True)),
                ('lab_tests_summary', models.TextField(blank=True)),
                ('complications_noted', models.TextField(blank=True, help_text='Notes on any high-risk complications')),
                ('medication_prescribed', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attending_staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'historical anc visit',
                'verbose_name_plural': 'historical anc visits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('ULTRASOUND', 'Ultrasound'), ('SCAN', 'Scan / X-Ray'), ('PRESCRIPTION', 'Prescription'), ('REFERRAL', 'Referral Letter'), ('CONSENT', 'Consent Form'), ('ID_DOCUMENT', 'ID Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/')),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
