# Generated by Django 6.0.5 on 2026-06-04 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancvisit',
            name='muac_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='urine_test_result',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='muac_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='urine_test_result',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
