# Generated by Django 5.0.9 on 2026-06-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_appointments_status_idx_and_more'),
        ('clinical', '0002_ancvisit_muac_cm_ancvisit_remarks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ancvisit',
            options={'ordering': ['-visit_date', '-created_at'], 'verbose_name': 'ANC Visit', 'verbose_name_plural': 'ANC Visits'},
        ),
        migrations.AlterModelOptions(
            name='historicalancvisit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ANC Visit', 'verbose_name_plural': 'historical ANC Visits'},
        ),
        migrations.RemoveField(
            model_name='ancvisit',
            name='lab_tests_summary',
        ),
        migrations.RemoveField(
            model_name='ancvisit',
            name='urine_test_result',
        ),
        migrations.RemoveField(
            model_name='historicalancvisit',
            name='lab_tests_summary',
        ),
        migrations.RemoveField(
            model_name='historicalancvisit',
            name='urine_test_result',
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='anemia_severity',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('MILD', 'Mild (10.0-10.9 g/dL)'), ('MODERATE', 'Moderate (7.0-9.9 g/dL)'), ('SEVERE', 'Severe (<7.0 g/dL)')], max_length=15),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Related appointment if this visit was from a scheduled appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anc_visit', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='blood_group_confirmed',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Blood Group (confirmed)'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='blood_sugar_mgdl',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Blood Sugar (mg/dL)'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='blood_sugar_type',
            field=models.CharField(blank=True, choices=[('FASTING', 'Fasting'), ('RANDOM', 'Random'), ('POSTPRANDIAL', 'Postprandial'), ('OGTT', 'OGTT')], help_text='Type of blood sugar test', max_length=20),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='health_education_given',
            field=models.TextField(blank=True, help_text='Health education topics covered'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='hepatitis_b_surface_ag',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('NOT_TESTED', 'Not Tested')], max_length=20, verbose_name='Hepatitis B Surface Ag'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('UNKNOWN', 'Unknown'), ('NOT_TESTED', 'Not Tested')], max_length=15, verbose_name='HIV Status'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='pulse_rate',
            field=models.IntegerField(blank=True, help_text='Pulse rate in bpm', null=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='rubella_igg',
            field=models.CharField(blank=True, choices=[('IMMUNE', 'Immune'), ('NON-IMMUNE', 'Non-Immune'), ('NOT_TESTED', 'Not Tested')], max_length=20, verbose_name='Rubella IgG'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='supplements_given',
            field=models.TextField(blank=True, help_text='Supplements provided (e.g., iron, folic acid)'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='syphilis_status',
            field=models.CharField(blank=True, choices=[('NON-REACTIVE', 'Non-Reactive'), ('REACTIVE', 'Reactive'), ('NOT_TESTED', 'Not Tested')], max_length=15, verbose_name='Syphilis Status'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='urine_glucose',
            field=models.CharField(choices=[('NIL', 'Nil'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NIL', max_length=3),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='urine_ketones',
            field=models.CharField(choices=[('NIL', 'Nil'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NIL', max_length=3),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='urine_protein',
            field=models.CharField(choices=[('NIL', 'Nil'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NIL', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='anemia_severity',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('MILD', 'Mild (10.0-10.9 g/dL)'), ('MODERATE', 'Moderate (7.0-9.9 g/dL)'), ('SEVERE', 'Severe (<7.0 g/dL)')], max_length=15),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='appointment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Related appointment if this visit was from a scheduled appointment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='blood_group_confirmed',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Blood Group (confirmed)'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='blood_sugar_mgdl',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Blood Sugar (mg/dL)'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='blood_sugar_type',
            field=models.CharField(blank=True, choices=[('FASTING', 'Fasting'), ('RANDOM', 'Random'), ('POSTPRANDIAL', 'Postprandial'), ('OGTT', 'OGTT')], help_text='Type of blood sugar test', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='health_education_given',
            field=models.TextField(blank=True, help_text='Health education topics covered'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='hepatitis_b_surface_ag',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('NOT_TESTED', 'Not Tested')], max_length=20, verbose_name='Hepatitis B Surface Ag'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('UNKNOWN', 'Unknown'), ('NOT_TESTED', 'Not Tested')], max_length=15, verbose_name='HIV Status'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='pulse_rate',
            field=models.IntegerField(blank=True, help_text='Pulse rate in bpm', null=True),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='rubella_igg',
            field=models.CharField(blank=True, choices=[('IMMUNE', 'Immune'), ('NON-IMMUNE', 'Non-Immune'), ('NOT_TESTED', 'Not Tested')], max_length=20, verbose_name='Rubella IgG'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='supplements_given',
            field=models.TextField(blank=True, help_text='Supplements provided (e.g., iron, folic acid)'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='syphilis_status',
            field=models.CharField(blank=True, choices=[('NON-REACTIVE', 'Non-Reactive'), ('REACTIVE', 'Reactive'), ('NOT_TESTED', 'Not Tested')], max_length=15, verbose_name='Syphilis Status'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='urine_glucose',
            field=models.CharField(choices=[('NIL', 'Nil'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NIL', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='urine_ketones',
            field=models.CharField(choices=[('NIL', 'Nil'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NIL', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalancvisit',
            name='urine_protein',
            field=models.CharField(choices=[('NIL', 'Nil'), ('+', '+'), ('++', '++'), ('+++', '+++')], default='NIL', max_length=3),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='bp_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic BP in mmHg', null=True),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='bp_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic BP in mmHg', null=True),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='fetal_heart_rate',
            field=models.IntegerField(blank=True, help_text='Fetal heart rate in bpm', null=True),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='fetal_presentation',
            field=models.CharField(blank=True, choices=[('CEPHALIC', 'Cephalic'), ('BREECH', 'Breech'), ('TRANSVERSE', 'Transverse')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='fundal_height_cm',
            field=models.IntegerField(blank=True, help_text='Fundal height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='hemoglobin_gdl',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Hemoglobin (g/dL)'),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='medication_prescribed',
            field=models.TextField(blank=True, help_text='Medications prescribed during this visit'),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='muac_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='MUAC (cm)'),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='ultrasound_results',
            field=models.TextField(blank=True, help_text='Ultrasound findings if performed'),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='bp_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic BP in mmHg', null=True),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='bp_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic BP in mmHg', null=True),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='fetal_heart_rate',
            field=models.IntegerField(blank=True, help_text='Fetal heart rate in bpm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='fetal_presentation',
            field=models.CharField(blank=True, choices=[('CEPHALIC', 'Cephalic'), ('BREECH', 'Breech'), ('TRANSVERSE', 'Transverse')], max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='fundal_height_cm',
            field=models.IntegerField(blank=True, help_text='Fundal height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='hemoglobin_gdl',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Hemoglobin (g/dL)'),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='medication_prescribed',
            field=models.TextField(blank=True, help_text='Medications prescribed during this visit'),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='muac_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='MUAC (cm)'),
        ),
        migrations.AlterField(
            model_name='historicalancvisit',
            name='ultrasound_results',
            field=models.TextField(blank=True, help_text='Ultrasound findings if performed'),
        ),
    ]
