# Generated by Django 6.0.5 on 2026-05-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('ANC1', 'ANC Visit 1'), ('ANC2', 'ANC Visit 2'), ('ANC3', 'ANC Visit 3'), ('ANC4', 'ANC Visit 4'), ('POSTNATAL_7DAY', 'Postnatal 7-Day Review'), ('POSTNATAL_6WEEK', 'Postnatal 6-Week Review'), ('OTHER', 'Other')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('attended_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ATTENDED', 'Attended'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
