# Generated by Django 6.0.5 on 2026-06-04 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_historicalappointment'),
        ('patients', '0006_patient_patients_edd_idx_patient_patients_risk_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointments_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date'], name='appointments_date_idx'),
        ),
    ]
