# Generated by Django 6.0.5 on 2026-06-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0007_historicalpatient_lang_patient_lang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMTCTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiv_status', models.CharField(choices=[('POSITIVE', 'HIV Positive'), ('NEGATIVE', 'HIV Negative'), ('UNKNOWN', 'Unknown'), ('DECLINED_TEST', 'Declined Test')], default='UNKNOWN', max_length=20)),
                ('test_date', models.DateField(blank=True, help_text='Date of HIV test', null=True)),
                ('arv_regimen', models.CharField(blank=True, help_text='ARV Regimen prescribed (if positive)', max_length=100)),
                ('arv_start_date', models.DateField(blank=True, help_text='Date ARV regimen was started', null=True)),
                ('viral_load', models.DecimalField(blank=True, decimal_places=2, help_text='Latest viral load value (copies/ml)', max_digits=10, null=True)),
                ('viral_load_date', models.DateField(blank=True, help_text='Date of latest viral load test', null=True)),
                ('cd4_count', models.IntegerField(blank=True, help_text='CD4 cell count (cells/mm3)', null=True)),
                ('infant_prophylaxis', models.BooleanField(default=False, help_text='True if infant ARV prophylaxis was administered')),
                ('infant_test_at_6wk', models.CharField(blank=True, help_text='Infant PCR test outcome at 6 weeks', max_length=50)),
                ('infant_test_at_18mo', models.CharField(blank=True, help_text='Infant antibody test outcome at 18 months', max_length=50)),
                ('disclosure_status', models.CharField(choices=[('DISCLOSED', 'Disclosed'), ('NOT_DISCLOSED', 'Not Disclosed')], default='NOT_DISCLOSED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, help_text='Staff counselor or clinician', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseled_pmtct_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(help_text='Patient linked to this PMTCT registry record', on_delete=django.db.models.deletion.CASCADE, related_name='pmtct_record', to='patients.patient')),
            ],
            options={
                'verbose_name': 'PMTCT Record',
                'verbose_name_plural': 'PMTCT Records',
                'db_table': 'pmtct_records',
            },
        ),
    ]
