# Generated by Django 6.0.5 on 2026-05-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostnatalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('NORMAL', 'Normal/Vaginal'), ('CAESAREAN', 'Caesarean Section'), ('ASSISTED', 'Assisted Delivery')], max_length=15)),
                ('baby_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('baby_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('mother_condition', models.CharField(blank=True, max_length=200)),
                ('baby_condition', models.CharField(blank=True, max_length=200)),
                ('review_7day_date', models.DateField(blank=True, null=True)),
                ('review_7day_attended', models.BooleanField(default=False)),
                ('review_7day_notes', models.TextField(blank=True)),
                ('review_6week_date', models.DateField(blank=True, null=True)),
                ('review_6week_attended', models.BooleanField(default=False)),
                ('review_6week_notes', models.TextField(blank=True)),
                ('bcg_given', models.BooleanField(default=False)),
                ('bcg_date', models.DateField(blank=True, null=True)),
                ('opv0_given', models.BooleanField(default=False)),
                ('opv0_date', models.DateField(blank=True, null=True)),
                ('hep_b_given', models.BooleanField(default=False)),
                ('hep_b_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postnatal_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postnatal_record', to='patients.patient')),
            ],
            options={
                'db_table': 'postnatal_records',
            },
        ),
    ]
