# Generated by Django 6.0.5 on 2026-05-23 17:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_historicalpartographentry_historicalpatient_and_more'),
        ('postnatal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPostnatalRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('NORMAL', 'Normal/Vaginal'), ('CAESAREAN', 'Caesarean Section'), ('ASSISTED', 'Assisted Delivery')], max_length=15)),
                ('baby_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('baby_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('mother_condition', models.CharField(blank=True, max_length=200)),
                ('baby_condition', models.CharField(blank=True, max_length=200)),
                ('review_7day_date', models.DateField(blank=True, null=True)),
                ('review_7day_attended', models.BooleanField(default=False)),
                ('review_7day_notes', models.TextField(blank=True)),
                ('review_6week_date', models.DateField(blank=True, null=True)),
                ('review_6week_attended', models.BooleanField(default=False)),
                ('review_6week_notes', models.TextField(blank=True)),
                ('bcg_given', models.BooleanField(default=False)),
                ('bcg_date', models.DateField(blank=True, null=True)),
                ('opv0_given', models.BooleanField(default=False)),
                ('opv0_date', models.DateField(blank=True, null=True)),
                ('hep_b_given', models.BooleanField(default=False)),
                ('hep_b_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient')),
            ],
            options={
                'verbose_name': 'historical postnatal record',
                'verbose_name_plural': 'historical postnatal records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
