# Generated by Django 6.0.5 on 2026-05-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_historicalpartographentry_historicalpatient_and_more'),
        ('postnatal', '0002_historicalpostnatalrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postnatalrecord',
            options={'ordering': ['-delivery_date']},
        ),
        migrations.AddField(
            model_name='historicalpostnatalrecord',
            name='pregnancy_number',
            field=models.PositiveIntegerField(default=1, help_text='Sequential pregnancy number for this patient (1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='postnatalrecord',
            name='pregnancy_number',
            field=models.PositiveIntegerField(default=1, help_text='Sequential pregnancy number for this patient (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='postnatalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnatal_records', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='postnatalrecord',
            unique_together={('patient', 'pregnancy_number')},
        ),
    ]
