# Generated by Django 6.0.5 on 2026-05-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postnatal', '0003_alter_postnatalrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostnatalrecord',
            name='apgar_score_1min',
            field=models.IntegerField(blank=True, help_text='APGAR score at 1 minute (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='historicalpostnatalrecord',
            name='apgar_score_5min',
            field=models.IntegerField(blank=True, help_text='APGAR score at 5 minutes (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='historicalpostnatalrecord',
            name='mental_health_screening',
            field=models.TextField(blank=True, help_text='Postpartum depression screening notes'),
        ),
        migrations.AddField(
            model_name='historicalpostnatalrecord',
            name='postpartum_complications',
            field=models.TextField(blank=True, help_text='Record any PPH, infections, or other complications.'),
        ),
        migrations.AddField(
            model_name='postnatalrecord',
            name='apgar_score_1min',
            field=models.IntegerField(blank=True, help_text='APGAR score at 1 minute (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='postnatalrecord',
            name='apgar_score_5min',
            field=models.IntegerField(blank=True, help_text='APGAR score at 5 minutes (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='postnatalrecord',
            name='mental_health_screening',
            field=models.TextField(blank=True, help_text='Postpartum depression screening notes'),
        ),
        migrations.AddField(
            model_name='postnatalrecord',
            name='postpartum_complications',
            field=models.TextField(blank=True, help_text='Record any PPH, infections, or other complications.'),
        ),
    ]
