# Generated by Django 5.0.9 on 2026-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postnatal', '0004_historicalpostnatalrecord_apgar_score_1min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostnatalrecord',
            name='baby_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalpostnatalrecord',
            name='baby_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='postnatalrecord',
            name='baby_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='postnatalrecord',
            name='baby_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
