# Generated by Django 5.0.9 on 2026-06-09 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Education Categories',
            },
        ),
        migrations.CreateModel(
            name='EducationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('audience', models.CharField(choices=[('DOCTOR', 'Doctors'), ('NURSE', 'Nurses'), ('PATIENT', 'Patients (Mothers)'), ('PARTNER', 'Partners'), ('ADOLESCENT', 'Adolescents'), ('ADMIN', 'Administrators')], max_length=20)),
                ('summary', models.TextField(help_text='Short summary for the list view')),
                ('content', models.TextField(help_text='Full educational content (HTML/Markdown supported)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='education.educationcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_procedures', models.ManyToManyField(blank=True, to='procedures.clinicalprocedure')),
                ('related_protocols', models.ManyToManyField(blank=True, to='procedures.emergencyprotocol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
