# Generated by Django 6.0.5 on 2026-05-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_historicalpartographentry_historicalpatient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NORMAL_DELIVERY', 'Normal Vaginal Delivery'), ('ASSISTED_DELIVERY', 'Assisted Delivery'), ('CAESAREAN', 'Caesarean Section Support'), ('BREECH', 'Breech Delivery'), ('MULTIPLE_DELIVERY', 'Twin/Multiple Delivery'), ('ANC_PROCEDURE', 'Antenatal Procedure'), ('POSTNATAL_CARE', 'Postnatal Care'), ('NEWBORN_CARE', 'Newborn Care'), ('INFECTION_PREVENTION', 'Infection Prevention')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Brief clinical summary')),
                ('severity', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=15)),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_procedures',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('PPH', 'Postpartum Hemorrhage'), ('ECLAMPSIA', 'Eclampsia / Pre-eclampsia'), ('OBSTRUCTED_LABOUR', 'Obstructed Labour'), ('NEONATAL_RESUS', 'Neonatal Resuscitation'), ('SEPSIS', 'Sepsis Management'), ('CORD_PROLAPSE', 'Cord Prolapse'), ('SHOULDER_DYSTOCIA', 'Shoulder Dystocia'), ('AMNIOTIC_EMBOLISM', 'Amniotic Fluid Embolism')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='🚨', max_length=10)),
                ('danger_signs', models.TextField(help_text='Key warning signs to recognize')),
                ('immediate_response', models.TextField(help_text='Step-by-step immediate action algorithm')),
                ('escalation_steps', models.TextField(help_text='When and how to escalate')),
                ('monitoring_requirements', models.TextField(blank=True)),
                ('referral_criteria', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_protocols',
                'ordering': ['emergency_type'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=200)),
                ('route', models.CharField(choices=[('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('RECTAL', 'Rectal'), ('TOPICAL', 'Topical')], max_length=15)),
                ('frequency', models.CharField(max_length=100)),
                ('max_dose', models.CharField(blank=True, max_length=100)),
                ('contraindications', models.TextField(blank=True)),
                ('important_notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='procedures.emergencyprotocol')),
            ],
            options={
                'db_table': 'emergency_drugs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('items', models.JSONField(default=list, help_text='Array of checklist items: [{"text": "...", "critical": true/false}]')),
                ('is_active', models.BooleanField(default=True)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='procedures.clinicalprocedure')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='procedures.emergencyprotocol')),
            ],
            options={
                'db_table': 'clinical_checklists',
            },
        ),
        migrations.CreateModel(
            name='ProcedureEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('procedures', models.ManyToManyField(blank=True, related_name='equipment', to='procedures.clinicalprocedure')),
                ('protocols', models.ManyToManyField(blank=True, related_name='equipment', to='procedures.emergencyprotocol')),
            ],
            options={
                'db_table': 'procedure_equipment',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, help_text='Patient context when protocol was accessed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='procedures.emergencyprotocol')),
            ],
            options={
                'db_table': 'protocol_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('warning_note', models.TextField(blank=True, help_text='Critical safety warning for this step')),
                ('estimated_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procedures.clinicalprocedure')),
            ],
            options={
                'db_table': 'procedure_steps',
                'ordering': ['step_number'],
                'unique_together': {('procedure', 'step_number')},
            },
        ),
    ]
