# Generated by Django 5.0.9 on 2026-06-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencydrug',
            name='route',
            field=models.CharField(choices=[('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('IV/IM', 'Intravenous/Intramuscular'), ('ORAL', 'Oral'), ('SUBLINGUAL', 'Sublingual'), ('RECTAL', 'Rectal'), ('Sublingual/Rectal', 'Sublingual/Rectal'), ('TOPICAL', 'Topical'), ('SC', 'Subcutaneous'), ('IV/Endotracheal', 'Intravenous/Endotracheal')], max_length=50),
        ),
    ]
