# Generated by Django 6.0.5 on 2026-05-28 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_historicalpatient_national_id_and_more'),
        ('postnatal', '0004_historicalpostnatalrecord_apgar_score_1min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('birth_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patients.patient')),
                ('postnatal_record', models.OneToOneField(blank=True, help_text='Link to the delivery record that spawned this child', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profile', to='postnatal.postnatalrecord')),
            ],
            options={
                'db_table': 'pediatrics_child_profile',
                'ordering': ['-date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='ChildClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('fever_illness_history', models.TextField(blank=True, help_text='History of fever or illnesses since last visit')),
                ('nutrition_status', models.TextField(blank=True, help_text='Breastfeeding, weaning, general nutrition')),
                ('development_milestones', models.TextField(blank=True, help_text='Milestones achieved (e.g. sitting, crawling)')),
                ('doctor_recommendations', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('attending_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='pediatrics.childprofile')),
            ],
            options={
                'db_table': 'pediatrics_clinic_visit',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes on nutrition, under-weight patterns, etc.')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='pediatrics.childprofile')),
            ],
            options={
                'db_table': 'pediatrics_growth_record',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('BCG', 'BCG'), ('OPV0', 'OPV 0'), ('OPV1', 'OPV 1'), ('OPV2', 'OPV 2'), ('OPV3', 'OPV 3'), ('PENTA1', 'Pentavalent 1'), ('PENTA2', 'Pentavalent 2'), ('PENTA3', 'Pentavalent 3'), ('ROTA1', 'Rotavirus 1'), ('ROTA2', 'Rotavirus 2'), ('MEASLES1', 'Measles 1 (9 months)'), ('MEASLES2', 'Measles 2 (18 months)'), ('VITAMIN_A', 'Vitamin A'), ('OTHER', 'Other')], max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GIVEN', 'Given'), ('MISSED', 'Missed')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pediatrics.childprofile')),
            ],
            options={
                'db_table': 'pediatrics_vaccination_record',
                'ordering': ['expected_date'],
            },
        ),
    ]
