# Generated by Django 6.0.5 on 2026-06-04 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pediatrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childclinicvisit',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='growthrecord',
            name='date_recorded',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
