# Generated by Django 5.0.9 on 2026-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pediatrics', '0002_alter_childclinicvisit_visit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine_name',
            field=models.CharField(choices=[('BCG', 'BCG'), ('OPV0', 'OPV 0'), ('OPV1', 'OPV 1'), ('OPV2', 'OPV 2'), ('OPV3', 'OPV 3'), ('PENTA1', 'Pentavalent 1'), ('PENTA2', 'Pentavalent 2'), ('PENTA3', 'Pentavalent 3'), ('PCV1', 'PCV 1'), ('PCV2', 'PCV 2'), ('PCV3', 'PCV 3'), ('ROTA1', 'Rotavirus 1'), ('ROTA2', 'Rotavirus 2'), ('IPV', 'IPV'), ('MEASLES_RUBELLA', 'Measles-Rubella (9 months)'), ('MEASLES2', 'Measles 2 (18 months)'), ('VITAMIN_A', 'Vitamin A'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
