# Generated by Django 6.0.5 on 2026-05-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], default='SMS', max_length=10),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='provider',
            field=models.CharField(choices=[('AFRICAS_TALKING', "Africa's Talking"), ('TWILIO', 'Twilio'), ('SMTP', 'SMTP Email'), ('MANUAL', 'Manual')], default='AFRICAS_TALKING', max_length=20),
        ),
    ]
