from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone
from tickets.services import create_ticket_notification
from tickets.models import Ticket
from users.models import StaffUser


class Command(BaseCommand):
    help = 'Send a test ticket notification (creates a test ticket or uses --ticket-id) and attempts to SMS admins'

    def add_arguments(self, parser):
        parser.add_argument('--ticket-id', type=int, help='Use an existing ticket id instead of creating a new one')
        parser.add_argument('--title', type=str, default='Test clinical ticket', help='Title for created test ticket')
        parser.add_argument('--description', type=str, default='This is a test ticket generated by management command', help='Description for created test ticket')
        parser.add_argument('--created-by', type=str, help='Email of the staff user to set as created_by (defaults to any active admin)')

    def handle(self, *args, **options):
        ticket_id = options.get('ticket_id')
        if ticket_id:
            try:
                ticket = Ticket.objects.get(pk=ticket_id)
            except Ticket.DoesNotExist:
                raise CommandError(f'Ticket with id={ticket_id} does not exist')
            self.stdout.write(self.style.SUCCESS(f'Using existing ticket id={ticket.pk}'))
        else:
            email = options.get('created_by')
            user = None
            if email:
                user = StaffUser.objects.filter(email=email, is_active=True).first()
                if not user:
                    raise CommandError(f'No active user found with email {email}')
            else:
                # fallback to any active admin or any active staff
                user = StaffUser.objects.filter(role='ADMIN', is_active=True).first() or StaffUser.objects.filter(is_active=True).first()
                if not user:
                    raise CommandError('No active staff user found to assign as created_by')

            ticket = Ticket.objects.create(
                title=options.get('title'),
                description=options.get('description'),
                priority='HIGH',
                created_by=user,
            )
            self.stdout.write(self.style.SUCCESS(f'Created test ticket id={ticket.pk}'))

        # Trigger notification + SMS logic
        try:
            create_ticket_notification(ticket)
            self.stdout.write(self.style.SUCCESS('Triggered create_ticket_notification (notifications and SMS attempts)'))
        except Exception as exc:
            raise CommandError(f'Failed to trigger notification: {exc}')
