# Generated by Django 6.0.5 on 2026-06-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Professional bio or about section'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed their initial profile setup'),
        ),
    ]
