# Generated by Django 6.0.5 on 2026-06-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staffuser_bio_staffuser_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='has_pmtct_permission',
            field=models.BooleanField(default=False, help_text='Designates if a Nurse has access to sensitive PMTCT registry data'),
        ),
    ]
