# Generated by Django 6.0.5 on 2026-06-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_merge_20260605_1319'),
        ('users', '0003_staffuser_has_pmtct_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='patient',
            field=models.OneToOneField(blank=True, help_text='Associated patient record if this is a Mother account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('MOTHER', 'Mother')], default='NURSE', max_length=20),
        ),
    ]
